Update pdnssoccli.py
CERN-CERT/pdnssoc-cli pull request #6
Opened 2024-02-22 18:12 UTC by 4quarks

Enhance error handling for misconfigurations in pdnssoccli.yml. Currently, it's difficult to identify the actual error if a typo is made

2024-02-27 15:45 UTC, arvchristos requested changes

2024-02-27 15:45 UTC, arvchristos commented on src/pdnssoccli/pdnssoccli.py
> +    except Exception as e:
We should refrain from using print for error logging. For this reason there is already a `logger` object declared. I suggest replacing this except block:


```suggestion
    except FileNotFoundError as e:
        logger.error("Configuration file {} not found. Exiting...".format(filename))
        exit(1)
    except:
        logger.error("Unexpected error while opening {} configuration file. Exiting...".format(filename))
        exit(1)
```

2024-03-05 18:55 UTC, 4quarks commented on src/pdnssoccli/pdnssoccli.py
> +    except Exception as e:
Sounds good!

2024-03-06 14:27 UTC, arvchristos approved these changes

2024-03-06 14:27 UTC, merged